### ISSUE TITLE
Inconsistent Charset error handling in native and JVM

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx-io#1]
JVM currently replaces all malformed input during decoding while Native silently ignores it.
`underflow`, `overflow`, `malformed` and `unmappable` flags should be consistent with JVM by default especially in the face of packed-based `Input`, where some error **should** be ignored until reading from the next packet of input, and some should be propagated or re-checked on next read, which potentially makes `Charset` usage error-prone

**Comment by fzhinkin** [comment]
We're rebooting the `kotlinx-io` development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it the issue will remain (or the feature is still missing) in a new version.
