### ISSUE TITLE
Duplicate of 'META-INF/kotlinx-io.kotlin_module'

### ISSUE THREAD

**Issue by RobertLK** [Kotlin/kotlinx-io#103]
Basically identical to https://github.com/Kotlin/kotlinx.coroutines/issues/1797 but affects multiplatform projects using kotlinx-io because the same module name exists in `kotlinx-io` and `kotlinx-io-jvm`.

Note even removing the `kotlinx-io:1.1.6` dependency doesn't help because it's also a dependency of `kotlin-stdlib-common`

```
        commonMain {
            dependencies {
                implementation kotlin('stdlib-common')
                implementation "org.jetbrains.kotlinx:kotlinx-io:$kotlinx_io_version"
            }
        }
        jvmMain {
            dependencies {
                implementation kotlin('stdlib')
                implementation "org.jetbrains.kotlinx:kotlinx-io-jvm:$kotlinx_io_version"
            }
```

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/kotlinx-io.kotlin_module'
```

Tested with AGP 3.6.1, kotlin 1.3.70

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
