### ISSUE TITLE
Compatibility with 1.3.7x 

### ISSUE THREAD

**Issue by martinbonnin** [Kotlin/kotlinx-io#105]
Trying to compile against version 0.1.16 with Kotlin 1.3.71, I get the following error:

```
 The abi versions don't match. Expected '[22]', found '17'
```

**Comment by Dominaezzz** [comment]
https://github.com/Kotlin/kotlinx-io/issues/54
https://github.com/Kotlin/kotlinx-io/issues/96

**Comment by saket** [comment]
It'd be great if this project could be bumped to Kotlin v1.3.72.

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
