### ISSUE TITLE
Compiler warning with using kotlinx.io.IOException

### ISSUE THREAD

**Issue by amanjeetsingh150** [Kotlin/kotlinx-io#110]
I striked while usage of `kotlinx.io.IOException` with this following compiler warning while doing some multiplatform I/O operations:

<img height="100" alt="Screenshot 2020-04-20 at 7 42 10 AM" src="https://user-images.githubusercontent.com/12881364/79707945-b4251800-82db-11ea-9250-0973ed73227d.png">

Writing the text if you are not able to read: `Using exception is an error. these classes accidentally slipped to the public api surface. We neither had intent to provide a production-quality implementation nor have an intent to support them. They are removed and to migrate, you can either use a corresponding java.io type or just a copy-paste implementation from the GitHub. If you have a use-case for multiplatform IO, please report it to the https://github.com/Kotlin/kotlinx-io/issues`

Have used the Github Implementation of IOException. But wanted to know what exactly happened are we not suppose to get it for this version or it will be available for future?

Currently have used the Github Implementation of IOException.

**Comment by Ktlo** [comment]
The same issue happened to me when I used `org.jetbrains.kotlinx:kotlinx-serialization-runtime` dependency. Kotlinx Serialization library also has `kotlinx.io.IOException` type alias and it's deprecated there. Maybe you have this dependency too.

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
