### ISSUE TITLE
Kotlin 1.4 native libraries

### ISSUE THREAD

**Issue by KirillObukhov** [Kotlin/kotlinx-io#117]
Trying to compile the multiplatform project with Kotlin 1.4 compiler I get an error about kotlinx-io-linuxx64 0.1.16 is a pre 1.4 library.
Could you please upload libraries compatible with new compiler?

**Comment by qwwdfsad** [comment]
0.1.16 and beyond was moved to `ktor-io` artifact under the Ktor umbrella.
The latest version is available here https://mvnrepository.com/artifact/io.ktor/ktor-io-jvm/1.4.1 and is compatible with Kotlin 1.4, please try it out

**Comment by saket** [comment]
Will it be useful to archive this repository and suggest people to use `ktor-io` instead?

**Comment by altavir** [comment]
@saket Kotlinx-io is in development and 0.2.0 version will be published sooner or later. Right now you can use my fork: https://bintray.com/mipt-npm/dev/kotlinx-io. It contains at least some native artifacts. Of course, no responsibility from JB.
