### ISSUE TITLE
kotlinx-io API as a trimmed-down Okio API

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/kotlinx-io#132]
As a starting point for https://github.com/Kotlin/kotlinx-io/issues/131, `kotlinx-io` API should be implemented as a trimmed-down version for Okio API. The API should include only core IO primitives and allow to build any other functionality on top of it.

Parts of the Okio API that are likely to be removed include:
- select API;
- hash functions API;
- cursor API;
- ByteStrings (will be added back later).

Some of these APIs provide specific functionality required by particular libraries and apps and could be implemented on top of the existing API; others are unsafe and should be redesigned to reduce possible user issues. It's also clear that these APIs were implemented as part of the core Okio library to squeeze additional performance out of it. To make sure that these APIs can be implemented using `kotlinx-io` without the loss of performance, the new APIs will be introduced in the future (or, if there will be no other way to implement removed functionality efficiently, it may be added back to the `kotlinx-io`).

The goal is to provide concise, well-documented and tested API. Core IO primitives API, like sources and sinks, should include as little functionality as possible; everything that could be implemented on top of it should be moved to extension functions or removed.

**Comment by qwwdfsad** [comment]
I would suggest starting with use cases that you are solving with an API (either Okio and/or obsolete Input/Output) to help us shape the overall direction. The same question stands for the implementation -- what exactly you do want to implement?

**Comment by qwwdfsad** [comment]
>I have two primary use-cases

These two use cases will be solvable with the proposed API shape and similar performance characteristics, I do not see issues with the proposed Okio-based design right off the bat.

**Comment by qwwdfsad** [comment]
We are happy to have any feedback about the API, and are keen on addressing known and yet unknown problems, whether they are about API shape, naming or performance characteristics.
We'll do an initial release soon, and I suggest you trying it.

Yet please consider being a bit more constructive -- the feedback "This API is more powerful and it would be nice to address it" is non-actionable for us and we cannot reasonably act on it
