### ISSUE TITLE
Implement ByteStrings

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/kotlinx-io#133]
Immutable array wrappers are ubiquitous in JVM ecosystem. These wrappers usually provide different handy methods like content-based equals/hashCode (allowing to use of such wrappers in hash-based data structures), string-like APIs to search for particular values or subsequences within a wrapper, copy or create a subsequence, and so on. Also, these wrappers guarantee that the backing array won’t change, no matter what. The latter allows to overcome the need for defensive array copies.

Okio already has ByteStrings, but these are intermingled with Okio internals. It would be nice to provide an implementation based on Okio ByteStrings, supported by `kotlinx-io`, but shipped as a different artifact so that users could include it in their projects separately.

**Comment by swankjesse** [comment]
Making Okio’s ByteString implement Comparable has proven quite handy in practice too.

For example, to deterministically order a bunch of protobufs I can sort by their encodings. Or perhaps I sort their hashes!

**Comment by fzhinkin** [comment]
Related issue: https://github.com/Kotlin/kotlinx-io/issues/115
