### ISSUE TITLE
Migrate to Kotlin's AutoCloseable from handrolled Closeable interface

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx-io#140]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-auto-closeable/

Note that it is an experimental interface (preliminary until Kotlin 2.0), but it shouldn't be an issue while we are in 0.x phase

**Comment by fzhinkin** [comment]
Seems like we have to wait until Kotlin 2.0 anyway: https://youtrack.jetbrains.com/issue/KT-55777

**Comment by qwwdfsad** [comment]
It seems we can just avoid FQN and it would do the trick though

**Comment by fzhinkin** [comment]
It's problematic as `RawSink` is an expect at the moment (to implement `java.io.Flushable` on JVM) and on JVM it won't compile as there is no actual for `AutoClosable`. Don't like it, but we can create `kotlinx.io.Flushable` expect, turn `RawSink` into a regular interface implementing both `kotlin.AutoClosable` and `kotlinx.io.Flushable` and actualize `Flushable` on JVM as `java.io.Flushable`. That should do the trick.

**Comment by fzhinkin** [comment]
I found the workaround, will switch to AutoCloseable then.
