### ISSUE TITLE
Break the curse of buildSrc and migrate to a more conventional build configuration

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx-io#142]
...while it's not too late.

`buildSrc` is rather a legacy from the early days of KTS adoption that we kept piggybacking on. It's accompanied by a steady yet manageable stream of minor issues, incompatibilities and general discomfort.

Would be nice to use composite builds (via `includeBuild`) instead

**Comment by shanshin** [comment]
Example of composite build in Kover https://github.com/Kotlin/kotlinx-kover/tree/main/build-logic. 
Also in Dokka https://github.com/Kotlin/dokka/tree/master/build-logic and [article](https://proandroiddev.com/stop-using-gradle-buildsrc-use-composite-builds-instead-3c38ac7a2ab3).

**Comment by EndzeitBegins** [comment]
Is using `buildSrc` still a problem? I was under the impression that with the newest Gradle versions `buildSrc` would behave mostly like an included build, e.g. [in of the Gradle docs](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources) it's said that:

> [...] The directory buildSrc is treated as an included build. [...]

In the [release notes of Gradle 8.x](https://gradle.org/whats-new/gradle-8/#build-configuration) it is also stated that:

> [...] At scale, sometimes included builds are more performant, and sometimes buildSrc are. The performance depends on how exactly things are structured. [...]
> In working towards the unification of buildSrc and included builds, buildSrc is changing to behave more like included builds. [...]
> If you’re using buildSrc already, keep using it and enjoy the new features. If you’re using included builds already, keep using them. [...]
