### ISSUE TITLE
Support mingwX64

### ISSUE THREAD

**Issue by Dominaezzz** [Kotlin/kotlinx-io#15]
I tried to use this in a multi-platform project and only the mingw target is not resolving the dependency.
Is there a reason why a KLIB for mingw hasn't been published?

**Comment by cy6erGn0m** [comment]
Not all tests passed on this platform. Need to setup a virtual machine with Windows to investigate why does it fail

**Comment by cy6erGn0m** [comment]
`0.1.0-alpha-24-rc13` is published with mingw target
