### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by joreilly** [Kotlin/kotlinx-io#164]
Any plans to add Wasm support? cc @bashor

**Comment by fzhinkin** [comment]
@joreilly Sorry for the long reply.

I'm considering supporting Wasm target at some point.
It can not be enabled by just plunking extra target into build configs, and it requires additional effort, so I'd rather postpone the support for later.

Do you already have use cases for `kotlinx-io` in Wasm targeting projects? Could you please provide more details? Thanks!

**Comment by martinbonnin** [comment]
Indeed, we've had requests for Wasm already ([issue](https://github.com/apollographql/apollo-kotlin/issues/4701)).

**Comment by joreilly** [comment]
btw you probably saw this already https://github.com/square/okio/issues/1203

**Comment by fzhinkin** [comment]
@joreilly @martinbonnin thank you for the details! I'll investigate what needs to be done to support Wasm then.

**Comment by fzhinkin** [comment]
Everything (except file systems) works fine after updating to 1.9.10.
