### ISSUE TITLE
Question: Implement custom multi-platform InputStream 

### ISSUE THREAD

**Issue by wollnyst** [Kotlin/kotlinx-io#17]
Hello,

I have asked the question on [StackOverflow](https://stackoverflow.com/questions/53014347/multi-platform-inputstream-alternative-in-kotlin), but didn't get any response there. So I'll try my luck here. 

I’m looking for a multi-platform alternative to input streams. My concrete task is to fetch an encrypted file from a remote server via https and decrypt it on demand.

In Java land I would an implement InputStream which proxies the reads to the input stream from the https library. How can I do the same in kotlin targeting multiple platforms.

I see ktor returns an ByteReadChannel, but I don’t know which functions.

I’m lost and don’t know where to start. Thanks for your help in advance.

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
