### ISSUE TITLE
Possible UB in ByteString hash function

### ISSUE THREAD

**Issue by MarkCMann** [Kotlin/kotlinx-io#190]
The ByteString hash function [caches previously calculated values](https://github.com/Kotlin/kotlinx-io/blob/1ee0a1df3673e9f610cdc4fd820344b5bc6851b7/bytestring/common/src/ByteString.kt#L107-L117). The member variable that stores the cached value is a [non-atomic `Int`](https://github.com/Kotlin/kotlinx-io/blob/1ee0a1df3673e9f610cdc4fd820344b5bc6851b7/bytestring/common/src/ByteString.kt#L72). 

I believe that kotlinx-ios hash cache logic was inspired by the [google protobuf ByteString hash implementation](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/ByteString.java#L981-L999). But that hash caching has a disclaimer that the [non-atomic `Int` backing the cache is safe because of JVM memory model semantics](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/ByteString.java#L139-L144). 

Is it safe to use a non-atomic `Int` for Kotlin native builds? Does the hash cache member variable need to be converted to an `Atomic<Int>` for non-JVM platforms?

**Comment by fzhinkin** [comment]
Thanks for reporting it!

There should be no issues on currently supported targets: on both X86_64 and Aarch64 (in fact, Aarch32, too) word-sized loads are atomic as long as an address is word-aligned (which should be true for a field).

But the fact that things work correctly right now should not be taken for granted, I'll check what could be done here.
