### ISSUE TITLE
Make filePath (String) available

### ISSUE THREAD

**Issue by Nailik** [Kotlin/kotlinx-io#206]
Currently it's not possible to read the actual Path as Text from the Path object.

Use cases are mostly native:
- sharing file
- playing with android media player (requires uri from file path)
- etc.

**Comment by fzhinkin** [comment]
I don't mind exposing the string w/ a path, but I'd also need to warn that `kotlinx.io.files` is experimental and subject to change or removal.

**Comment by Nailik** [comment]
@fzhinkin well it would make it easier because you could use it when parsing json data or as i said when you want to perform native actions and use the Path class commonly. This way you could then use on android the java File class and do whatever needs to be done instead of holding String and when necessary making a Path object etc etc.
