### ISSUE TITLE
Basic filesystems support for Wasm target

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/kotlinx-io#217]
There's no FS support for Wasm, although it could be implemented on top of the WASI.

**Comment by fzhinkin** [comment]
First part, enabling filesystems for wasmJs: https://github.com/Kotlin/kotlinx-io/pull/256

**Comment by sureshg** [comment]
@fzhinkin just for the clarify when you say `wasmJs`, it's for running on node and not on browser and browser won't get file system support due to security sandboxing..rt?

**Comment by fzhinkin** [comment]
@sureshg, yes, that's correct. Browsers don't provide a _proper_ fs API (well, there's a [FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem), but that's a whole different story), so when it comes to JS, `kotlinx.io.files` works only in NodeJs (or, theoretically, any other server-side JS engine compatible with Node).
However, there's a [memfs](https://www.npmjs.com/package/memfs) library bringing an in-memory filesystem to browsers and providing node:fs-compatible API. It needs to be checked, but I guess it might allow using `kotlinx-io` fs-support in browsers.

**Comment by fzhinkin** [comment]
And the wasmWasi support: https://github.com/Kotlin/kotlinx-io/pull/257
