### ISSUE TITLE
Reuse allcocated arrays

### ISSUE THREAD

**Issue by hgourvest** [Kotlin/kotlinx-io#250]
There's no function for writing to a ByteArray pre-allocated in the Source interface. 
Such a function would allow us to be more efficient by reusing memory.

```
fun read(dest: ByteArray, startIndex: Int, endIndex: Int) {
...
}
```

**Comment by fzhinkin** [comment]
@hgourvest do you mean a function to access an array backing the source's buffer or a function to read data from a source into an array?

If the latter, then it's already there: https://github.com/Kotlin/kotlinx-io/blob/2f4196f8b27418c2166263b882a5c5190c7b91c7/core/common/src/Sources.kt#L267

**Comment by hgourvest** [comment]
@fzhinkin Exactly, I totally missed this function. Thank you!
