### ISSUE TITLE
Cannot get position from Source

### ISSUE THREAD

**Issue by CharlieTap** [Kotlin/kotlinx-io#254]
This is more of a question than anything else, it doesn't seem possible to get the position of stream from the API. Is this a design choice?

I ask because I have a scenario where I'm decoding a leb128 encoding int, and I'm having to return both the decoded int and the bytes consumed up the call stack because the encoding is variable and I need to understand the bytes consumed in order to calculate other parts of the binary.

If we had a position function available it mean I could just track the change in position at a high level

**Comment by fzhinkin** [comment]
Unfortunately, there's no way to reliably account for the number of bytes consumed from the Source as it exposes its buffer and allows direct consumption from it.
