### ISSUE TITLE
Add `ByteString` conversions for JVM `ByteBuffer`

### ISSUE THREAD

**Issue by joffrey-bion** [Kotlin/kotlinx-io#269]
In the same vibe as https://github.com/Kotlin/kotlinx-io/issues/266 and https://github.com/Kotlin/kotlinx-io/issues/268, it would be nice to have built-in conversions in `kotlinx-io-bytestring` for the JVM `ByteBuffer` type for a full multi-platform experience.

Examples:
```kotlin
/**
 * Exposes the contents of this [ByteString] as a read-only [ByteBuffer] without copying data.
 */
fun ByteString.asReadOnlyByteBuffer(): ByteBuffer = ByteBuffer.wrap(getBackingArrayReference()).asReadOnlyBuffer()

/**
 * Reads all remaining bytes in this [ByteBuffer] into a new [ByteString].
 */
fun ByteBuffer.readByteString(): ByteString = ByteString.wrap(readByteArray())

/**
 * Reads all remaining bytes in this [ByteBuffer] into a new [ByteArray].
 */
// private because that's not really the role of kotlinx-io-bytestring, more of the stdlib
private fun ByteBuffer.readByteArray(): ByteArray {
    val array = ByteArray(remaining())
    get(array)
    return array
}
```

Arguably the last one could be a stdlib function instead.

**Comment by joffrey-bion** [comment]
Note: this might overlap with (or be superseded by) https://github.com/Kotlin/kotlinx-io/issues/239

**Comment by fzhinkin** [comment]
@joffrey-bion We already have set of functions wrapping Sinks, Sources, and Buffers into Channels, as well as functions allowing to read/write `Buffer` from/to `ByteBuffer`. And there doesn't seem to be a lot of adoption.

Are there any scenarios where proposed functions could be used indeed? Would existing NIO-centric extensions work there?

**Comment by joffrey-bion** [comment]
> Are there any scenarios where proposed functions could be used indeed?

Yes, this is also something I use in Krossbow to wrap the Java web socket APIs.

> Would existing NIO-centric extensions work there?

Which extensions are you referring to? In my case the goal is to bridge `ByteBuffer`s (that I get from Java APIs) to `ByteString`s (that I expose in my Kotlin API) in the most efficient way.
It could be ok to go through other intermediate representations if this didn't incur more copies than necessary.

**Comment by fzhinkin** [comment]
> Which extensions are you referring to?

- https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io/as-byte-channel.html
- https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io/transfer-from.html
- https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io/read-at-most-to.html
- https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io/write.html

> It could be ok to go through other intermediate representations if this didn't incur more copies than necessary.

But yeah, the use of any of those from above implies additional copies. :(

**Comment by joffrey-bion** [comment]
Thanks! Ok that was my understanding, so yeah I would still need these more direct helpers then.
