### ISSUE TITLE
NullPointerException in readStringImpl on JVM

### ISSUE THREAD

**Issue by lopcode** [Kotlin/kotlinx-io#279]
Hi there,

I've been playing around with this library for a personal project, and I'm bumping up against some rare issues. I understand that it's pre-release, but I feel like it's related to segment pooling so thought I would raise an issue in case you aren't already aware of it. For context the project is an HTTP framework, and I'm experimenting with Loom for fun.

The `kotlinx-io` version I'm using is `0.3.1`, compiling for Java 21, and Kotlin `1.9.22`.

`kotlinx-io` functions great in "no pressure" scenarios, but during a simulated load test, around 1 in 100k HTTP calls fail in my framework due to a mixture of odd exceptions bubbling up and strings getting sliced in odd ways. The most common one I can reproduce is an NPE, shown below:

```
Exception in thread "pellet-virtual-10" java.lang.NullPointerException
	at kotlinx.io.Segment.pop(Segment.kt:105)
	at kotlinx.io.SourcesJvmKt.readStringImpl(SourcesJvm.kt:49)
	at kotlinx.io.SourcesJvmKt.readString(SourcesJvm.kt:71)
	at dev.pellet.server.extension.BufferExtensionsKt.stringifyAndClear(BufferExtensions.kt:10)
	at dev.pellet.server.codec.http.HTTPMessageCodec.handleHeaderLine(HTTPMessageCodec.kt:218)
	at dev.pellet.server.codec.http.HTTPMessageCodec.consume(HTTPMessageCodec.kt:84)
	at dev.pellet.server.socket.BlockingSocketHandler.handle(BlockingSocketHandler.kt:21)
	at dev.pellet.server.socket.BlockingSocketAccepter.accept$lambda$1$lambda$0(BlockingSocketAccepter.kt:42)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```

In the HTTP framework, a new `Buffer` is created for every socket, and only used from a single virtual thread, so I'm not sure it's related to threading issues - but even if it was, and I've messed something up, I wouldn't expect exceptions coming from inside the library?

I've pushed my work-in-progress branch up, and I've been encountering these issues running `NoContentBenchmarkTest`: https://github.com/lopcode/Pellet/tree/task/loom-kotlinx-io - it's a bit messy though so might be easier for you to write smaller stress tests to try and reproduce this issue. The circumstances that feel relevant to me are:
* Lots of new `Buffer` allocations, from lots of different virtual threads
* Lots of relatively small writes (comprised of a couple of `\r\n` terminated HTTP lines, potentially written in separate attempts due to the nature of network calls)
  * Followed by a buffer clear

Let me know if any other information would be helpful too, happy to help.

**Comment by fzhinkin** [comment]
@lopcode, thanks for reaching us out regarding the issue.

I was able to reproduce the issue, but not quite sure what's causing it. 

> I'm not sure it's related to threading issues - but even if it was, and I've messed something up, I wouldn't expect exceptions coming from inside the library?

kotlinx-io IO primitives are not thread safe and the behavior is undefined if these primitives are used concurrently from several different threads.

But it doesn't looks like Pellet server shares a single Buffer between multiple threads.

I'll continue debugging the problem this week and will return with the conclusion (hopefully, I'll manage to find one 🤞 ).

**Comment by lopcode** [comment]
That makes a lot of sense! I'll check this out after I'm done travelling for work, thanks for investigating.

When the time's right and there's more documentation for the library, it might be worth adding a section on thread safety and symptoms of threading issues like this too
