### ISSUE TITLE
This lib has no functions for unsigned types?

### ISSUE THREAD

**Issue by SuperOP535** [Kotlin/kotlinx-io#28]
I'm using `BytePacketBuilder` and there's for example writeByte function but not writeUByte, am I doing something wrong or is this not a feature (yet)? I'm using KotlinJS btw.

**Comment by cy6erGn0m** [comment]
It is missing yet. sorry

**Comment by cy6erGn0m** [comment]
Unsigned integers support is introduced for non-async primitives since 0.1.5
