### ISSUE TITLE
Path uses io.File instead of nio.Path

### ISSUE THREAD

**Issue by SPC-code** [Kotlin/kotlinx-io#296]
https://github.com/Kotlin/kotlinx-io/blob/bae3fe3e9b6141ceb13df204c7413c8bbb9ae078/core/jvm/src/files/PathsJvm.kt#L13

Current Path implementation uses java.io.File instead of java.nio.Path inside. I think that nio.Path is a better alternative. Any File could be converted to a Path, but not vice versa. Path provides a way to access custom file systems and has a better design.

I think it makes sense to replace io.File with nio.Path.

**Comment by fzhinkin** [comment]
Files are used instead of Paths for compatibility with older Android versions. We may eventually stop supporting them, but not now.

**Comment by JakeWharton** [comment]
Keep in mind those numbers represent only devices which talk to Google Play which is not representative of the entire Android ecosystem.

**Comment by fzhinkin** [comment]
We're also striving to provide compatibility with the same API Level as Okio, so there are no plans to make any changes here currently.
