### ISSUE TITLE
ByteReadPacket Does Not Respect ByteOrder

### ISSUE THREAD

**Issue by bkenn** [Kotlin/kotlinx-io#30]
[ShapeTest.tar.gz](https://github.com/Kotlin/kotlinx-io/files/2753363/ShapeTest.tar.gz)

Hello. I am loving the work done here to support io-processing in multiplaform. Thank you for your hard work. I have found a bug with ByteReadPacket not respecting byteOrder. I have attached a reproducible example. You can find the functions in shape.shapefile.kt commonMain. The two tests are in jvmTest.

**Comment by cy6erGn0m** [comment]
Fixed in 0.1.4
