### ISSUE TITLE
Float reading and writing is inconstent on Kotlin JS

### ISSUE THREAD

**Issue by Burtan** [Kotlin/kotlinx-io#322]
Hey,
the following snippet
```
"test float to bytes" {
    val buffer = Buffer()
    buffer.writeFloat(0.999f)
    buffer.readFloat() shouldBe 0.999f
}
```
gives this result.
```
AssertionFailedError:
Expected :0.999
Actual   :0.9990000128746033
```

JVM works fine.

**Comment by fzhinkin** [comment]
As `writeFloat`/`readFloat` [documentation](https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io/read-float.html) [stated](https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io/write-float.html), these functions use `Float.toBits` and `Float.fromBits` to serialize floats to bitstream and back.
On JS, Floats have a wider range (as they are backed by Number, which is an IEEE 745 double-prevision 64-bit floating point number), so `Float.toBits` may produce numbers that are not equal to initial values ([see docs](https://kotlinlang.org/api/latest/js/stdlib/kotlin/to-bits.html)).

The only thing we can improve here is stressing this peculiarity in docs.

**Comment by Burtan** [comment]
Thanks for the clarification. As there is also writeDouble/readDouble, this is very unexpected if you don't know that JS is only using 64-bit floating points underneath. I don't know if it is possible to trim the float values to 32-bit precision stored in a 64-bit variable?

**Comment by fzhinkin** [comment]
> I don't know if it is possible to trim the float values to 32-bit precision stored in a 64-bit variable?

Sure, it's possible, but with potential precision loss (which is always the case for values that could not be represented exactly, like `0.999`).

While JS Numbers are always double-precision floating point numbers, JS also provides [TypedArrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Typed_arrays), where values have fixed width in binary representation. When writing values into these arrays, 64-bit fp Numbers are converted to an arrays' type (in fact, [semantics](https://tc39.es/ecma262/multipage/structured-data.html#sec-setvalueinbuffer) is defined for storing in array's buffer, with the float64 to float32 conversion described [here](https://tc39.es/ecma262/multipage/structured-data.html#sec-numerictorawbytes)).

To "trim" double-precision fp to a single-precision fp, Kotlin's `Float.toBits` [uses](https://github.com/JetBrains/kotlin/blob/ea3649b7c7ca2a3ea87aecee0ea5f4805e5831f5/libraries/stdlib/js/runtime/bitUtils.kt#L38) typed arrays with a shared buffer to extract Float's binary representation. As a result, we can get 4 bytes representing a IEEE 754 single-precision fp that was obtained by rounding double-precision `Number` backing the `Float`.

`Float.fromBits` performs transformation in the opposite direction, but reading a value from JS `Float32Array` converts it back to `Number` with [mantissa least significant bits being "zero-padded"](https://pl.kotl.in/aYGWKqU-s), leading to `0.999f` not being equal to `Float.fromBits(0.999f.toBits())`.

**Comment by Burtan** [comment]
https://youtrack.jetbrains.com/issue/KT-24975/Enforce-range-of-Float-type-in-JS
