### ISSUE TITLE
ERROR: SystemFileSystem.list() Unresolved reference 'list'.

### ISSUE THREAD

**Issue by mahramane** [Kotlin/kotlinx-io#329]
Hi 
When i use `SystemFileSystem.list()` in `jvm` i get the following error:

`Unresolved reference 'list'`

**Comment by fzhinkin** [comment]
@mahramane, could you please provide more details about your environment (like Kotlin version, kotlinx-io version) and how to reproduce an issue?

**Comment by mahramane** [comment]
> @mahramane, could you please provide more details about your environment (like Kotlin version, kotlinx-io version) and how to reproduce an issue?

i use kotlin multiplatform, kotlin 2.0.0-RC03, kotlin io 0.3.5.
when i run project in mac os i get that error.

**Comment by mahramane** [comment]
in android it worked.

**Comment by fzhinkin** [comment]
Do you have a code snippet reproducing the issue? 

At first glance, there are no issues with `list`, Kotlin 2.0, and kotlinx-io 0.3.5, at least on a simple test case: https://github.com/fzhinkin/kx-io-329/blob/a7671328925e480c262733df3ac450237e067cb2/src/commonTest/kotlin/KxIo329Reproducer.kt#L11

**Comment by mahramane** [comment]
Oh. my bad. i fixe it. thank you.
