### ISSUE TITLE
[help] How to read and write a file?

### ISSUE THREAD

**Issue by lucasmsoares96** [Kotlin/kotlinx-io#358]
I'm having trouble finding information about reading and writing files with kotlinx-io. How to do this?

**Comment by fzhinkin** [comment]
You can use [FileSystem.sink
](https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io.files/-file-system/sink.html) to open a ‘RawSink’ for writing into a file, and [FileSystem.source](https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io.files/-file-system/source.html) to open a ‘RawSource’ for reading.

Both functions could be called on the [SystemFileSystem](https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io.files/-system-file-system.html) object.

**Comment by lucasmsoares96** [comment]
It's not clear what I do with the source and the sink. Could you share an example?

**Comment by mipastgt** [comment]
Maybe a little example helps.
```
    val testResultsDirPath: Path = ...

    @Test
    fun testBasicFile() {
        val path = Path(testResultsDirPath, "kotlinio.txt")

        SystemFileSystem.delete(path)
        assertFalse(SystemFileSystem.exists(path))

        SystemFileSystem.sink(path).buffered().use {
            it.writeString("example")
        }

        SystemFileSystem.source(path).buffered().use {
            assertEquals("example", it.readLine())
        }
    }


```

**Comment by lucasmsoares96** [comment]
It works, thanks!
