### ISSUE TITLE
Add a way to check if Path points to a link

### ISSUE THREAD

**Issue by vdshb** [Kotlin/kotlinx-io#359]
I can see `Path.isDirectory` and `Path.isRegularFile` but I can't see a way to detect symbolic link.

This is a proposal to add `Path.isSymbolicLink` and `Path.isHardLink` properties which detect whether `Path` points into symbolic/hard link or not.

**Comment by vdshb** [comment]
I'll put it here as a reference: https://docs.oracle.com/javase/tutorial/essential/io/links.html

I'm not an expert in this field, so maybe `Path.isHardLink` is harder/impossible to implement. In this case, this proposal is only about `Path.isSymbolicLink`.

**Comment by fzhinkin** [comment]
Similar issue: https://github.com/Kotlin/kotlinx-io/issues/330
