### ISSUE TITLE
`readFromHead`/`writeToTail` should propagate the `Int` returned from the lambda

### ISSUE THREAD

**Issue by JakeWharton** [Kotlin/kotlinx-io#360]
I'm trying to implement `RawSource.readAtMostTo` using `UnsafeBufferOperations.writeToTail`.

I want to do
```kotlin
	override fun readAtMostTo(sink: Buffer, byteCount: Long): Long {
		return UnsafeBufferOperations.writeToTail(sink, 1) { bytes, startIndexInclusive, endIndexExclusive ->
			val read: Int = TODO()
			read
		}.toLong()
	}
```
but `writeToTail` doesn't give me the `Int` which I return from the lambda at the callsite in order to do this.

**Comment by JakeWharton** [comment]
Expanding this to `readFromHead` since you can end up reading fewer than requested with things like POSIX `write`.

**Comment by fzhinkin** [comment]
There are a few JVM-specific extensions allowing to read/write from/to `java.nio.ByteBuffer`. It might be worth updating those functions too.
