### ISSUE TITLE
Temporary file creation support

### ISSUE THREAD

**Issue by feliperce** [Kotlin/kotlinx-io#391]
Hello, it's possible to create a temporary file like in jvm File.createTempFile()?

**Comment by JakeWharton** [comment]
You can use https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io.files/-system-temporary-directory.html to get the location of the system temp dir. Producing a random file name, creating the file, and (optionally) deleting it when you're done are up to you using the regular FS APIs.

**Comment by JakeWharton** [comment]
Kotlin 2.0.20's `Uuid.random()` is an excellent source of randomness for a name suffix, btw!

**Comment by feliperce** [comment]
> You can use https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io.files/-system-temporary-directory.html to get the location of the system temp dir. Producing a random file name, creating the file, and (optionally) deleting it when you're done are up to you using the regular FS APIs.



> You can use https://kotlin.github.io/kotlinx-io/kotlinx-io-core/kotlinx.io.files/-system-temporary-directory.html to get the location of the system temp dir. Producing a random file name, creating the file, and (optionally) deleting it when you're done are up to you using the regular FS APIs.

Woow, I hadn't found that, thank you!
it worked

**Comment by JakeWharton** [comment]
Maybe consider changing `SystemFileSystem` from a `val` to an `object`, so that this creation function and other APIs like that temp path can be hung off of it?

**Comment by cloudshiftchris** [comment]
> Maybe consider changing `SystemFileSystem` from a `val` to an `object`, so that this creation function and other APIs like that temp path can be hung off of it?

This forces all temporary files into that one location; it may be the case that one wants to create temp files elsewhere.

**Comment by JakeWharton** [comment]
That's correct, and is the entire point of the temporary path provided by the OS which is available solely on the system file system.

If you want to create a temporary file elsewhere on the system file system or within file systems other than the system file system then you are free to do so on your own.
