### ISSUE TITLE
Web crash `get_os().platform() == 'win32'`

### ISSUE THREAD

**Issue by raspberry-jenshen** [Kotlin/kotlinx-io#394]
Hello!

Thank you for your cool package!

I faced issues when I converted my Kotlin code to the web platform (JS).

My code: 
```
internal class FileSystemImpl(
    private val fileSystem: KotlinFiles = SystemFileSystem,
) : FileSystem {
```

The crash:
`platform  undefined`

The crash happens when FileSystemImpl is created.

```
// JS code
var properties_initialized_FileSystemJs_kt_lg8f5i;
  function _init_properties_FileSystemJs_kt__4boaac() {
    if (!properties_initialized_FileSystemJs_kt_lg8f5i) {
      properties_initialized_FileSystemJs_kt_lg8f5i = true;
      SystemFileSystem = new SystemFileSystem$1();
      // crash is here
      isWindows = get_os().platform() == 'win32';
    }
  }
```

**Comment by fzhinkin** [comment]
@raspberry-jenshen `SystemFileSystem` is not supported for JS/Browser. It's supported only for NodeJS environment.

**Comment by raspberry-jenshen** [comment]
Oh, I see, please improve the documentation then

Couse, you have this target.

<img width="268" alt="Screenshot 2024-09-25 at 13 42 20" src="https://github.com/user-attachments/assets/4b175721-b3db-49cf-becb-20cf413f050c">
