### ISSUE TITLE
okio <> kotlinxio converter

### ISSUE THREAD

**Issue by vanniktech** [Kotlin/kotlinx-io#415]
Ktor3 has started adopting kotlinxio which is nice. All my other code base still uses okio. Are there any plans to provide a converter module similar to the [RxJava2/RxJava3 Bridge](https://github.com/akarnokd/RxJavaBridge) where on can convert between the respective `Source` & `Buffer` implementations of both libraries?

**Comment by JakeWharton** [comment]
This is tracked by #178

**Comment by fzhinkin** [comment]
There are plans to provide a converter module (see the issue Jake had referred, #178 ), but there are no concrete dates so far.
