### ISSUE TITLE
MPP JS client: Can't resolve 'text-encoding'

### ISSUE THREAD

**Issue by epool** [Kotlin/kotlinx-io#49]
COPIED FROM: https://github.com/ktorio/ktor/issues/961
=============
**Ktor Version**
1.1.2

**Ktor Engine Used(client or server and name)**
Ktor client with default engine

**JVM Version, Operating System and Relevant Context**
JDK 1.8, Windows, Kotlin JS

**Feedback**
We are using the ktor client in a multiplatform project (android, iOS and web). Starting with version 1.1.0 the build of the JS client fails with the following message:

```
ERROR in ./kotlinx-io.js
Module not found: Error: Can't resolve 'text-encoding' in '<mypath>\kotlinmultiplatform\web\build\kotlin-js-min\main'
@ ./kotlinx-io.js 5309:21-45 5320:21-45
@ ./ktor-utils.js
@ ./web.js
```

If I manually add `text-encoding` as a npm-dependeny, it works.

If I list the npm dependency tree with the previous working ktor version 1.0.1 I get:

```
+-- kotlinx-io@0.1.4 -> <mypath>\kotlinmultiplatform\web\build\node_modules_imported\kotlinx-io extraneous
+-- kotlinx-io-js@0.1.1 -> <mypath>\kotlinmultiplatform\web\build\node_modules_imported\kotlinx-io-js
| +-- kotlin@1.3.10
| +-- kotlin-test@1.3.10
| | `-- kotlin@1.3.10 deduped
| +-- kotlinx-atomicfu@0.11.12 -> <mypath>\kotlinmultiplatform\web\build\node_modules_imported\kotlinx-atomicfu deduped
| `-- text-encoding@0.7.0
```
If I list the npm dependency tree with a ktor version >= 1.1.0 the `kotlinx-io-js` (and of course `text-encoding`) is missing

**Comment by dhakehurst** [comment]
see #57  for workaround
