### ISSUE TITLE
Is this library active/supported?

### ISSUE THREAD

**Issue by dryajov** [Kotlin/kotlinx-io#54]
I'm very interested in using this library in an upcoming https://libp2p.io/ jvm implementation and I'm wondering what's it's current status. Is it under active development, ready for production or abandoned?

Furthermore, if this is still actively developed/maintained what are it's future plans, is there a roadmap of some sort?

**Comment by polson** [comment]
Guess not

**Comment by IgorKey** [comment]
@e5l , up. Hi there, could u please explain the differences between this lib and ktor-io. Are the synchronized or what?

**Comment by e5l** [comment]
Sure. The previous version of this library is archived and bundled in `ktor` with the name `ktor-io`.

The next library is in active development, we're trying different approaches and testing it against the old version.
