### ISSUE TITLE
0.1.13 fails with new JS plugin

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx-io#57]
```
ERROR in .._imported/kotlinx-io/0.1.13/kotlinx-io.js
Module not found: Error: Can't resolve 'text-encoding' in 'D:\Work\Projects\dataforge-core\build\js\packages_imported\kotlinx-io\0.1.13'
```

**Comment by JesseCorbett** [comment]
I'm running into this issue as well. It's resulting in ktor-js being entirely unusable for me. Any odds we can see this issue addressed soon?

**Comment by altavir** [comment]
The workaround is to add `api(npm("text-encoding"))` to JS platform dependencies. It gives a warning about unmaintained dependency, but works.

**Comment by Ribesg** [comment]
Just encountered this as well!

**Comment by dhakehurst** [comment]
me too.
Thanks to @altavir for the work-around tip.
I find that I solved this in two parts,
for the browser,
add to package.json
```
"browser": {
    "text-encoding": false,
    "ws": false,
    "fs": false,
    "path": false,
    "os": false,
    "crypto": false,
    "stream": false,
    "http": false,
    "tls": false,
    "zlib": false,
    "https": false,
    "net": false
  }
```

then for the tests (which fail also with this problem)
```
kotlin {
    sourceSets {
        val jsTest by getting {
            dependencies {
                api(npm("text-encoding"))
            }
        }
    }
}
```

**Comment by gincwang** [comment]
Hello I'm trying to add this to my gradle (in groovy) but it's not recognizing the `npm` command, is that another plugin we have to add?  `Could not get unknown property 'npm' for object of type org.jetbrains.kotlin.gradle.plugin.mpp.DefaultKotlinDependencyHandler`

**Comment by gincwang** [comment]
nvm I got it working with this syntax for groovy
```
jsMain {
    dependencies {
        implementation npm("text-encoding", 0.7.0)
    }
}
```

**Comment by joffrey-bion** [comment]
I had the same issue and added the `npm()` dependency, but it is quite annoying. I actually found out that my own mutliplatform libraries don't publish their npm dependencies either, and require the users to add the npm dependencies to their gradle files just like this.

Not sure if this is the intended behaviour :/

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
