### ISSUE TITLE
Windows HANDLE Input/Output

### ISSUE THREAD

**Issue by Xfel** [Kotlin/kotlinx-io#61]
Not sure if this is the right format.

I recently needed a winapi HANDLE based Input/Output implementation, so I implemented one. I would like make a pull request for it, but I don't know how to integrate windows-specific code into the current project structure.

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
