### ISSUE TITLE
CharsetEncoder.encodeToImpl does not terminate with unicode surrogates

### ISSUE THREAD

**Issue by steffenkleinle** [Kotlin/kotlinx-io#63]
CharsetEncoder.encodeToImpl() does not terminate when calling it with e.g. `\uD800\uDCA6` (𐂦) . I'm currently using kotlinx.io v 1.1.4.

**Comment by stuebingerb** [comment]
We are seeing this in kotlinx-io-jvm 0.1.16

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
