### ISSUE TITLE
The core may be duplicated with Okio2?

### ISSUE THREAD

**Issue by rantianhua** [Kotlin/kotlinx-io#75]
Okio 2 is also making an effort to multiplatform base on kotlin. And the functions provided by core are supported by Okio. So, why not to concern to use Okio to as kotlin-io library? Or, what's the main difference between this library and Okio?

**Comment by joffrey-bion** [comment]
I'm also wondering where this is going. 

It would be nice to have a unified effort at building an efficient multiplatform I/O library for Kotlin, unless of course there is a notable difference between the 2 approaches that may suit different needs and would justify 2 I/O libraries.

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
