### ISSUE TITLE
Decide upon length type

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx-io#84]
There should be a design decision about default type for lengths and offsets. Currently, it is `Int` in most places, but in some cases like file IO it could be `Long`. Also, it is possible to use `UInt`.

**Comment by qwwdfsad** [comment]
We have this decision, most of the core API is `Int` (because of JVM API and JS limitations), but we also provide extension overloads with longs, so users won't have to write annoying `toInt()` everywhere

**Comment by altavir** [comment]
OK, We should add it to the documentation. We will need to also decide on whether we want to support large files.
