### ISSUE TITLE
Modify decodeUTF8Chars to gracefully treat end of input

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx-io#85]
To properly evaluate end of file and safely treat trailing read symbol after `\r` in `readUTF8Line`. I do not see safe way to implement it without changing how `decodeUTF8Chars` works. Trying to call `eof()` inside condition does not work because of inline nature of the method.

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
