### ISSUE TITLE
Serial communication

### ISSUE THREAD

**Issue by InfRandomness** [Kotlin/kotlinx-io#87]
Hello everyone, I would like to know if this library had support for communication over serial for receiving packets and sending them back. Thanks in advance.

**Comment by AlexCouch** [comment]
I think this library is on hold cause of kotlinx-coroutines and flow. It's pretty important for an io library to be fully backboned by a stable well structured efficient async library like flow. As it seems, this io library is going to be easily expandable so it'd be pretty simple to add serial support.

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
