### ISSUE TITLE
[io-2] Bytes#append makes limits array too big

### ISSUE THREAD

**Issue by pull-vert** [Kotlin/kotlinx-io#89]
In Bytes#append function, limits seems to grow too big.
This is current code with a comment that shows the problem
```kotlin
if (tail == buffers.size) {
    buffers = buffers.copyInto(arrayOfNulls(buffers.size * 2))
    // buffers has now a size = 2 * old size
    limits = limits.copyInto(IntArray(buffers.size * 2))
    // FIXME incorrect ! here limits size = 2 * new buffer size = 4 * old buffer size
    // should be equal to new buffer size
}
```

**Comment by fzhinkin** [comment]
We're rebooting the kotlinx-io development (see https://github.com/Kotlin/kotlinx-io/issues/131), all issues related to the previous versions will be closed. Consider reopening it if the issue remains (or the feature is still missing) in a new version.
