### ISSUE TITLE
Ktor-io or kotlinx-io?

### ISSUE THREAD

**Issue by Him188** [Kotlin/kotlinx-io#96]
I've found that ktor-io is very similar to kotlinx-io. 
Which one should I use?

**Comment by e5l** [comment]
Hi, @Him188. Thanks for the question. The ktor-io library is a frozen version of old kotlinx-io. Now the new version of kotlinx-io is in active design and development.
 
So if you need a stable solution to solve your problem, I would recommend you to stay with ktor-io; 

Btw ktor-io has some pitfalls that we're trying to solve in the new version, and if you want to experiment with that, you should choose kotlinx-io for sure.
