### ISSUE TITLE
How to add JsonPrimitive into JsonObejct

### ISSUE THREAD

**Issue by roths** [Kotlin/kotlinx-io#97]
Recently, I convert my lib to support cross platform. There are plenty JSONObject to access data.I just need few value in nested json struct, so i dont want to use @Serializable.When i try to put a value into JsonObject, i cant find the sample code.

**Comment by altavir** [comment]
What does it have to do with IO? You probably wanted to write [here](https://github.com/Kotlin/kotlinx.serialization).

**Comment by e5l** [comment]
Consider reporting the problem in kotlinx.serialization issue tracker. Closed
